config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :songs do
    resources :likes, only: [:create, :destroy]
  end
  resources :perfumes
  get 'sindanurl'=> 'perfumes#index'
  get 'myurl'=> 'users#show'
  get 'sinkiurl'=> 'songs#new'
  root 'songs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :song
  belongs_to :user
  validates_uniqueness_of :song_id, scope: :user_id
end

app/models/perfume.rb
class Perfume < ApplicationRecord

end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         mount_uploader :image, ImageUploader
         has_many :songs
         has_many :songs, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_songs, through: :likes, source: :song
         has_many :songs, dependent: :destroy
         validates :name, presence: true
         validates :profile, length: { maximum: 200 }
         def already_liked?(song)
          self.likes.exists?(song_id: song.id)
         end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(song_id: params[:song_id])  
        redirect_back(fallback_location: root_path)
    end

    def destroy
        like = Like.find_by(song_id: params[:song_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
        def index
        end
      
        def new
          @perfume = Perfume.new
        end
      
        def show
          @perfume = Perfume.find_by(id: params[:id])
        end
      
        def create
          @perfume = Perfume.new(perfume_params)
          params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
          if @perfume.save
              flash[:notice] = "診断が完了しました"
              redirect_to perfume_path(@perfume.id)
          else
              redirect_to :action => "new"
          end
        end
      
      private
        def perfume_params
            params.require(:perfume).permit(:question1, :question2, :question3, :question4)
        end
      
      
      
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!
     def top
     end
     
     def index
      @Songs = Song.all.order(created_at: :desc)
        if params[:search] == nil
            @songs= Song.all.order(created_at: :desc)
         elsif params[:search] == ''
            @songs= Song.all
         else
            @songs= Song.where("title LIKE ? OR name LIKE ? OR genre LIKE ?",'%' + params[:search] + '%','%' + params[:search] + '%' ,'%' + params[:search] + '%')
         end
         @rank_songs = Song.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}
         @songs = @songs.page(params[:page]).per(6)
         @rank_songs = Kaminari.paginate_array(@rank_songs).page(params[:page]).per(10)

     end


     def new
        @song = Song.new
      end
    
      def create
        song = Song.new(song_params)
        song.user_id = current_user.id
        if song.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        song = Song.find(params[:id])
        song.destroy
        redirect_to action: :index
      end

      

      private
      def song_params
        params.require(:song).permit(:name, :title, :genre, :coment, :day, :youtube_url, :question, :body)
      end




    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
    def find_youtube_url(youtube_url)
        if youtube_url[0..16] == "https://youtu.be/"
          return youtube_url[17..27]
        # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
        else
          return youtube_url[32..42]
        # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
        end
    end    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+JP:wght@300&family=Shippori+Mincho+B1:wght@500;700&display=swap" rel="stylesheet">

    <title>Music</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--いいね機能について-->
    <script src="https://kit.fontawesome.com/116ddc6897.js" crossorigin="anonymous"></script> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <h1><%= link_to songs_path do %>
    <div class="header_menu_top"></div>
  <% end %></h1>
  <div class="header-list">
  
  <ul>
    <li><%= link_to "トップページ", songs_path %></li>
    <li><%= link_to "気分診断", perfumes_path %></li>
    <% if user_signed_in? %>
    <li><%= link_to "マイページ", user_path(current_user.id) %></li>
    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    <li><%= link_to "新規投稿",new_song_path %></li>
    <% else %>
    <li><%= link_to "ログイン", new_user_session_path %></li>
    <li><%= link_to "新規登録", new_user_registration_path %></li>
    <% end %>
    
  </ul>
  </div>
</header>
<main>
  <%= yield %>
</main>
<footer>
    R
    </footer>
  </body>
</html>

app/views/perfumes/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>香水診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        

    <div class="sindan">
        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_perfume_path, class: "link" %>
        </div>
    </div>
    </body>
    
    

app/views/perfumes/new.html.erb
<div class="sindan">
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="perfume-container">
        <div class="col-12">
            <p>Q1. 今の気分は…</p>
        </div>
        <div class="col-6">


            <%= f.radio_button :question1, "1", id: "custom_id1" %>
            <label for="custom_id1">＋</label>
            <%= f.radio_button :question1, "2", id: "custom_id2" %>
            <label for="custom_id2">－</label>
        </div>
        <div class="col-12">
            <p>Q2. どの時間で音楽をききたい？…</p>
        </div> 
        <div class="col-6">
            <%= f.radio_button :question2, "1", id: "custom_id3" %>
            <label for="custom_id3">朝</label>
            <%= f.radio_button :question2, "2", id: "custom_id4" %>
            <label for="custom_id4">夜</label>
        </div>   
        <div class="col-12">
            <p>Q3. 今日の予定は…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question3, "1", id: "custom_id5" %>
            <label for="custom_id5">仕事、学校</label>
            <%= f.radio_button :question3, "2", id: "custom_id6" %>
            <label for="custom_id6">遊び、特になし</label>
        </div>
    
        <div class="col-12">
            <p>Q4. 今求めているものは…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question4, "1", id: "custom_id7" %>
            <label for="custom_id7">共感、明るさ</label>
            <%= f.radio_button :question4, "2", id: "custom_id8" %>
            <label for="custom_id8">悲しさ、特になし</label>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit " 結果 " %>
    </div>
<% end %>
</div>

app/views/songs/index.html.erb


<div class="toukou">
<h3>投稿を検索</h3>
<%= form_tag({controller:"songs",action:"index"}, method: :get) do  %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する' %>
 <% end %>
</div>

<div class="song">
  <% @songs.each do |t| %>
<div class="orikaesi">
<div class="tikatika">    
<div class="tika"><iframe width="200" height="200" src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br></div>
  <ul> 
  <br>
   <li> <div class="font0"><%= t.name %></div></li>
  <br>
   <li><div class="font1"><%= t.title %></div></li>
  <br>
   <li><div class="font2"><%= t.genre %></div><li>
  <br>
   <li><div class="font3"><%= t.comment %></div></li>
  <br>
   <li><%= link_to t.user.name, user_path(t.user.id) %></li>
  </ul>
</div>



<!--以下いいね機能-->
   <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to song_like_path(id: t.id, song_id: t.id), method: :delete do %>
            <br> 
            <i class="fa-regular fa-heart"></i></i><%= t.likes.count %>
           
           <% end %>
       <% else %>
           <%= link_to song_likes_path(id: t.id, song_id: t.id), method: :post do %>
               <p>いいね</p><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="fa-regular fa-heart"></i></i><%= t.likes.count %>
   <% end %>
</div>
   <% end %>
</div>

<!--以下ページネーション機能-->
<div class="page">
<%= paginate @songs %>
</div>


<div class="rankingu">
<br><h1>いいねランキング</h1>
<% @rank_songs.each do |t| %>
  <iframe width="1000" height="400" src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br>
  <%= t.name %>
    <%= t.title %>
    <i class="far fa-heart"></i><%= t.likes.count %>
    
   <br>
   
<% end %> 
<%= paginate @rank_songs %>
</div>

<div class="irasuto">
<a href="sindanurl">
  <%= image_tag 'kibun.png', class:"image1" %>
</a>

<a href="/users/<%= current_user.id %>">
  <%= image_tag 'my.png', class:"image2" %>
</a>

<a href="sinkiurl">
  <%= image_tag 'sinki.png', class:"image3" %>
</a>
</div>







app/views/songs/new.html.erb
<div class="sinki">
<h3>新規投稿ページ</h3>
<%= form_for @song do |f| %>
  <div class="field5">
  <%= f.label :youtube_url %>
  　<%= f.text_field :youtube_url, :size => 140 %>
  </div>

    <div class="field4">
    <%= f.label :曲名 %>
    <%= f.text_field :title, :size => 140 %>
    </div>

  <div class="field3">
    <%= f.label :アーティスト %>
    <%= f.text_field :name, :size => 140 %>
  </div>

  <div class="field2">
    <%= f.label :ジャンル  %>
    <%= f.select :genre, 
    [["テンションが上がる曲", "テンションが上がる曲"], 
    ["励まされる曲", "励まされる曲"], 
    ["エモい曲", "エモい曲"],
    ["恋愛ソング", "恋愛ソング"]], include_blank: "選択して下さい" %>
  </div>


  <div class="field1">
    <%= f.label :コメント  %>
    <%= f.text_area :comment, :size => "30x2" %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>  
</div>

app/views/songs/show.html.erb
<h1>GeekTwitter</h1>
<h3>Song詳細</h3>
<div class="song">
  <p><%= @song.title %></p>
  <p><%= @song.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@song) %>
        <%= link_to song_like_path(@song), method: :delete do %>
            <i class="fas fa-heart"></i><%= @song.likes.count %>
        <% end %>
      <% else %>
        <%= link_to song_likes_path(@song), method: :post do %>
          <i class="fa-regular fa-heart"></i></i><%= @song.likes.count %>
        <% end %>
       <% end %>
      <% else %>
      <i class="fa-regular fa-heart"></i></i><%= @song.likes.count %>
      <% end %>
 < %= link_to "編集する", edit_song_path(@song.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @song.liked_users.each do |user| %>
    <li><%= user.email %></li>
<% end %>


app/views/songs/top.html.erb
<%= link_to '一覧へ',  songs_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb

<div class="totaro">
<p>名前 : <%= @user.name %></p>
<p><%= image_tag @user.image_url, size: "250x200" if @user.image? %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<br> 
<% @user.songs.each do |t| %>
  <%= t.user.name %>
  <%= t.title %>
  <%= button_to "削除する", song_path(t.id), method: :delete %>
<% end %> 

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<br>
<% @user.liked_songs.each do |t| %>
  <%= t.user.name %>
  <%= t.title %>
<% end %>
<!-- ここまで-->
<br>
<%= link_to "トップページに戻る", songs_path %>
</div>